### PR TITLE
fixes for Debian based Operating Systems

### PR DESCRIPTION
**Pull request by Spidy123222**
Title speaks its self review the commits.

### CODE REVIEW

**Comment by jkcoxson** [comment]
Is there a reason that you changed everything from apt to apt get?

**Comment by Spidy123222** [comment]
> Is there a reason that you changed everything from apt to apt get?

Only thing that got changed from apt to apt-get was apt install git.

Rasbian doesn't respond well all the time to apt so apt-get got it working.

**Comment by Spidy123222** [comment]
> Is there a reason that you changed everything from apt to apt get?

Is it good other than that?

**Comment by jkcoxson** [comment]
For posterity, these conflicts were resolved over Discord

**Pull request merged**
